### ISSUE TITLE
Top-Down-Ansicht erstellen + Pfad + rviz implementieren

### ISSUE THREAD

**Issue by ebertzci** [ll7/paf21-2#17]
Definition of Done:
- Top-down-ansicht als topic in eigenem package bereitstellen
- Pfad mit array aus Koordinaten sichtbar machen
- Rviz Panel erstellen

**Comment by Nikkulin3** [comment]
Implementierung von zwei Pfaden (local/global) jeweils durch Angabe von carla-Koordinaten.
Hell- und Dunkelmodus und Dict für die Farben leicht änderbar.
Rotations- und North-is-up-Modus sowie Ganze-Karte-Modus möglich.
Anzeige von: 2 Pfade, Ampelfarbe, Mittellinien, Spurmarkierungen, Straßen, Fußgänger und Fahrzeuge.
Topic: /paf/validation/top_down_map
![image](https://user-images.githubusercontent.com/40068769/141962541-68d06a5b-4f3b-47f5-882d-8c6c5b4bfef5.png)
