### ISSUE TITLE
MapManager: alte Aufgabe fertigstellen

### ISSUE THREAD

**Issue by ebertzci** [ll7/paf21-2#21]
Definition of Done:
- restliche Karten anschauen und groben Überblick gewinnen, wie "richtig" die Karteninformationen sind
- Code eigenständig zum laufen bringen (also unabhängig von psaf-1)

**Comment by jkruess** [comment]
Code zum laufen bringen: -> Neues Issue, weil grundlegende Veränderungen nötig (CommonRoad Scenario Designer)
