### ISSUE TITLE
Map Manager: Fehlerbehebung

### ISSUE THREAD

**Issue by ebertzci** [ll7/paf21-2#36]
Definition of Done:
- [x] Fehler aus dem Map Manager von psaf-1 beheben
- [x] wenn möglich (und für andere Teammitgleider nötig): bei neuen Fehlerbehebungen ausgegebene Karten-Dateien speichern und weitergeben
- [x] wenn nötig auch händisch im Common Road Scenario Designer 
- [x] Ziel: Merge

**Comment by ebertzci** [comment]
altes Issue: #23

**Comment by jkruess** [comment]
Zuerst Fehlerbehebung und Enhancement für den CRDesigner nötig
