### ISSUE TITLE
Architektur vom letzten Jahr zum laufen bringen und testen

### ISSUE THREAD

**Issue by Nikkulin3** [ll7/paf21-2#5]

**Comment by Nikkulin3** [comment]
Potentielle Verbesserungsmöglichkeiten und was funktioniert gut / nicht so gut.

**Comment by ebertzci** [comment]
Definition of Done:
- Codestand von den alten Teams zum laufen bringen (und quasi den Wettbewerb ausführen)
- Anschauen, welche Sachen gut funktionieren und wo es noch Verbesserungspotential gibt
