### ISSUE TITLE
Implement backward driving as option

### ISSUE THREAD

**Issue by JulianStockmann** [ll7/paf21-2#50]
- [x] Create the path message for the local planner to include a backward driving option, waypoints, and target speed.
- [x] Change the acting package to react to the flag by activating the rear gear and inverting the steering for backward driving.

DoD:
- [x] The path message exists with the above-described parameters.
- [x] The acting package reacts to the messages as described above.

**Comment by RolandZimmermann** [comment]
Additional testing was done with a dummy script. Details can be found [here](https://github.com/ll7/paf21-2/blob/50-Implement-backward-driving/Docs/paf_acting/backwards/reverse.md) 

Conclusion:
- It is only good enough, if there are many points on the path. We therefore suggest to use a spline to fill some points inbetween
- We can drive backwards as fast as forward
- We can switch between forward and backward
- We can do a U-Turn forwards and backwards
- We fixed some bugs in the old code
