### ISSUE TITLE
Implement and test an emergency break.

### ISSUE THREAD

**Issue by JulianStockmann** [ll7/paf21-2#51]
- [x] Add messages/parameters for an emergency break and return to path following.
- [x] Adjust the actor to react to the messages by switching between a full stop and path following.

DoD:
- [x] Subscriber and dummy publisher for the messages.
- [x] The actor reacts to the messages.

**Comment by RolandZimmermann** [comment]
Bool is used to go into emergency mode. We tested different actions to get the lowest time in breaking, see [here](https://github.com/ll7/paf21-2/blob/%2351-Implement-and-test-emergency-break/Docs/paf_acting/backwards/braking.md) for more.

Result is: Reverse, 30° steer, Throttle 100%, handbrake

if the signal to do an emergency break is False, we go into default mode
