### ISSUE TITLE
Test curve behaviour

### ISSUE THREAD

**Issue by JulianStockmann** [ll7/paf21-2#52]
- [x] Test how the vehicle follows a curve at different speeds.
- [x] Test the difference between 3 or more points per curve.

DoD:
- [x] Speeds 30, 50, and 100 Km/h tested.
- [x] Tested 2 different point densities (3, >3).

**Comment by RolandZimmermann** [comment]
The vehicle starts drifting (if the speed is high in a curve), like a rally car (fast curve traversal possible)
