### ISSUE TITLE
Fix the Stanley Controller

### ISSUE THREAD

**Issue by JulianStockmann** [ll7/paf21-2#53]
The steering doesn't work properly when the current_speed is not 0.

DoD:
The steering works independently of the speed.

**Comment by JulianStockmann** [comment]
The Stanley Controller needs at least the following two points to calculate the target orientation and the steering.
If the distance between the car and the next point is greater than 20 meters, the steering get's shaky.

**Comment by RolandZimmermann** [comment]
Some additional insides and fixes got implemented in the Issue/Branch #50. These will get merged by the next sprint
